// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tspdorasqadfcantgaax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzcGRvcmFzcWFkZmNhbnRnYWF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NDQ5OTksImV4cCI6MjA2NzUyMDk5OX0.WuY4xEi5c2Pf2TCDHKWyz9MBTg9ABSBKnD4VDjvUaH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});